# United States - Crime Rates - 1960 - 2014

### Introduction:

This time you will create a data 

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [47]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.

In [61]:
crime=pd.read_csv("US_Crime_Rates_1960_2014.csv")
crime.head(10)

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800
5,1965,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
6,1966,195576000,5223500,430180,4793300,11040,25820,157990,235330,1410100,2822000,561200
7,1967,197457000,5903400,499930,5403500,12240,27620,202910,257160,1632100,3111600,659800
8,1968,199399000,6720200,595010,6125200,13800,31670,262840,286700,1858900,3482700,783600
9,1969,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500

In [49]:
crime.info()

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                55 non-null     int64
 1   Population          55 non-null     int64
 2   Total               55 non-null     int64
 3   Violent             55 non-null     int64
 4   Property            55 non-null     int64
 5   Murder              55 non-null     int64
 6   Forcible_Rape       55 non-null     int64
 7   Robbery             55 non-null     int64
 8   Aggravated_assault  55 non-null     int64
 9   Burglary            55 non-null     int64
 10  Larceny_Theft       55 non-null     int64
 11  Vehicle_Theft       55 non-null     int64
dtypes: int64(12)
memory usage: 5.3 KB

In [50]:
crime.shape
crime.axes

[RangeIndex(start=0, stop=55, step=1),
 Index(['Year', 'Population', 'Total', 'Violent', 'Property', 'Murder',
        'Forcible_Rape', 'Robbery', 'Aggravated_assault', 'Burglary',
        'Larceny_Theft', 'Vehicle_Theft'],
       dtype='str')]

### Step 4. What is the type of the columns?

In [51]:
crime.dtypes

Year                  int64
Population            int64
Total                 int64
Violent               int64
Property              int64
Murder                int64
Forcible_Rape         int64
Robbery               int64
Aggravated_assault    int64
Burglary              int64
Larceny_Theft         int64
Vehicle_Theft         int64
dtype: object

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

In [52]:
# crime["Year"] = pd.to_datetime(crime["Year"].astype(str), format="mixed")
# crime.head()

### Step 6. Set the Year column as the index of the dataframe

In [56]:
#crime.set_index("Year",inplace=True)
crime.head()

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

### Step 7. Delete the Total column

In [63]:
crime.drop(columns=["Total"],inplace=True)
crime.head()

,Year,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1960,179323175,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1,1961,182992000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
2,1962,185771000,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
3,1963,188483000,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
4,1964,191141000,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

In [71]:
df=pd.read_csv("US_Crime_Rates_1960_2014.csv")
df.head()
df["Decade"]=(df["Year"]//10)*10
df["Decade"]
#df.groupby("Decade").sum()
df.groupby("Decade")["Population"].sum()

Decade
1960    1915053175
1970    2121193298
1980    2371370069
1990    2612825258
2000    2947969117
2010    1570146307
Name: Population, dtype: int64

### Step 9. What is the most dangerous decade to live in the US?

In [85]:
crime_total=df.groupby("Decade")["Total"].sum()
dangerous_decade=crime_total.idxmax()
dangerous_decade
# max_total_idx=df.Total.idxmax()
# dangerous_decade=df.loc[max_total_idx]
# dangerous_decade

np.int64(1990)